### PR TITLE
Update quick_start.md

### PR DESCRIPTION
**Pull request by thigg**
Windows need ". commands do not run with '

### CODE REVIEW

**Comment by gruppjo** [comment]
Hi thigg, this is mentioned here: https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/windows.md

**Comment by thigg** [comment]
At least I didn't saw it, so it might be userful to link it a few more times in prominent places?

**Comment by gruppjo** [comment]
It's the first bullet under **App Development** in our guides section. Where would you put it? https://github.com/mwaylabs/generator-m-ionic#guides

**Comment by gruppjo** [comment]
I'm planning to overhaul some of the documentation. I think I'll include a note in more places for windows users! https://github.com/mwaylabs/generator-m-ionic/issues/356

**Pull request closed without merging**
