### PR TITLE
point plist module to a commit that fixes the plist generation with e…

### PR DESCRIPTION
**Pull request by funkybaboon**
Fix issue with empty plist keys by using @lordgreg's solution 

See https://github.com/mwaylabs/generator-m-ionic/pull/442

### CODE REVIEW

**Comment by gruppjo** [comment]
Hey everybody, thanks for shedding some light.

Since this is only a workaround I'd rather open an issue with a descriptions on how to fix this until a fixed version of `plist.js` is available. If we lock the version of `plist` to a specific commit, we'll need to revert this change in a later version.

So I see two options:

1. publish a bugfix version of the generator, but one of you will have to keep in mind to revert the version lock of `plist` once it's fixed
1. instead we open an issue with a short description on how to deal with this problem until it fixes itself without any changes in the generator.

@funkybaboon, @MathiasTim, @lordgreg, @DrMabuse23 please vote with 👍 for option 1. or 👎 for option 2.

**Comment by MathiasTim** [comment]
I have to vote 👍  we are having (not just here) some issues with keeping versions *soft* with e.g.  `cordova: "^6.0.0"` instead of `cordova: "~6.0.0". Because people do breaking changes in feature releases. Thats why im completely fine with *hardcoding* to a specific commit because in my opinion it's easier to maintain then the other way round.

**Comment by gruppjo** [comment]
@funkybaboon, welcome to the team :)

**Comment by gruppjo** [comment]
@lordgreg, @MathiasTim, @funkybaboon. Published in version `1.10.1` https://github.com/mwaylabs/generator-m-ionic/releases/tag/1.10.1

Please keep me updated, I don't want to see this dependency become unnecessarily outdated. @lordgred, will you let me know?

**Comment by lordgreg** [comment]
@gruppjo Maybe. 🎱

**Comment by gruppjo** [comment]
Ever heard of `npm unpublish`? #npmgate #youbetter

**Pull request merged**
